Dockerfile: add dependencies for lede environment
CreatorDev/creator-docker pull request #5
Opened 2017-03-14 10:07 UTC by nikhil-zinjurde-imgtec

Include additional dependencies as mentioned in https://lede-project.org/docs/user-guide/imagebuilder#prerequisites

Signed-off-by: Nikhil Zinjurde <nikhil.zinjurde@imgtec.com>

2017-03-14 10:40 UTC, Ham22 requested changes
Where did this list of changes come from?
The official docs provide a table of known deps here https://lede-project.org/docs/guide-developer/install-buildsystem#table_of_known_prerequisites. Some seem to be missing.

2017-03-14 10:40 UTC, Ham22 commented on Dockerfile
> +build-essential bsdmainutils ccache cmake gettext xsltproc wget \
I have left ccache disabled in the builds as it is unlikely to give us any benefit due to the current build system arch of using containers. We can enable and possibly mount the cache out to a volume to reap the full benefits.

2017-03-14 10:40 UTC, Ham22 commented on Dockerfile
> -build-essential bsdmainutils cmake device-tree-compiler \
Why are you moving wget and device-tree-compiler, the lines are attempting to have a logical split of 
stuff that builds things and stuff that gets things which this change breaks needlessly.

2017-03-14 11:24 UTC, nikhil-zinjurde-imgtec commented on Dockerfile
> -build-essential bsdmainutils cmake device-tree-compiler \
Restored the logical split

2017-03-14 12:09 UTC, Ham22 commented
Btw does this fix any known issues? Whats the motivation?

2017-03-15 05:10 UTC, nikhil-zinjurde-imgtec commented
This is to have a build environment to build LEDE from source, SDK and ImageBuilder.  There are not known issues yet without including these dependencies

2017-03-16 09:32 UTC, Ham22 commented on Dockerfile
> +asciidoc fastjar gettext intltool patch ruby sdcc xsltproc \
Coud you drop:
* patch is part of build-essential
* sdcc is a constrained device compiler for devices we will never use

2017-03-16 15:00 UTC, Ham22 approved these changes

2017-03-17 04:50 UTC, merged